stages:
  checkpoint:
    cmd: python utils/select_checkpoint.py
    deps:
    - params.yaml
    outs:
    - data/checkpoint.ckpt
  train:
    cmd: ionice -c3 python train.py --use_experiment_yaml
    deps:
    - experiment.yaml
    - data/checkpoint.ckpt
    - modules/
    - nets
    - train.py
    - utils
    params:
    - model
    - train
    outs:
    - data/checkpoints
    - data/comet_ml
  setup:
    cmd: python utils/setup_experiment.py
    outs:
    - experiment.yaml:
        persist: true
        cache: false
    always_changed: true
