dataset:
        #size: [640, 360]
        size: [1280, 720]
        train-dataset: "data/nuscenes-complete-15x10/train"
        valid-dataset: "data/nuscenes-complete-15x10/valid"

train:
        learning-rate: 0.01
        lr-decay: 0.9
        lr_decay_step_size: 2
        batch-size: 2
        weight_decay: 0.0004

        epochs: 15

        checkpoint-interval: 1

model:
        encoder_decoder_name: "linknet"
        encoder_decoder:
                encoder_name: "vgg16"
                #encoder_weights: null
                encoder_weights: "imagenet"
                in_channels: 4
                encoder_depth: 2
                classes: 64
                activation: "sigmoid"
                decoder_use_batchnorm: true

        head: 
                branches:
                        
                        in_channels: [64, 8, 8]
                        out_channels: [8, 8, 1]
                        kernel_sizes: [3, 3, 1]
                        strides: 1
                        padding: [1,1,0]
                        dilation: 1
                        batch_norm: True
                        end_activation: "relu"
        
                
