dataset:
        name: "road_boundary_dataset"
        size: [640, 360]
        #size: [1280, 720]
        #size: null
        train-dataset: "data/nuscenes-complete-15x10/train"
        valid-dataset: "data/nuscenes-complete-15x10/valid"
        test-dataset: "data/nuscenes-complete-15x10/test"

train:
        learning-rate: 0.03
        lr-decay: 0.1
        lr_decay_step_size: 1
        batch-size: 4
        weight_decay: 1e-5

        loss: "mse"
        loss-args: 
                reduction: "mean"

        epochs: 50
        validation-interval: 500
        validation-batches: 100

        logger-interval: 100
        nmbr-logged-images: 9
        checkpoint-interval: 1

model: !include nets/smp_linknet.yaml
        
                
