dataset:
        name: "road_boundary_dataset"
        #size: [640, 360]
        #size: [1280, 720]
        size: null
        train-dataset: "data/nuscenes-complete-15x10/train"
        valid-dataset: "data/nuscenes-complete-15x10/valid"
        test-dataset: "data/nuscenes-complete-15x10/test"

train:
        learning-rate: 0.05
        lr-decay: 0.1
        lr_decay_step_size: 1
        batch-size: 4
        weight_decay: 1e-1

        losses: 
                distance_loss: 
                        loss: "mse"
                        factor: 10.0
                        args:
                                reduction: "mean"
                end_loss: 
                        loss: "bce"
                        factor: 10.0
                        args:
                                reduction: "mean"
                direction_loss: 
                        loss: "cosine_similarity"
                        factor: 1.0
                        args:
                                reduction: "mean"

        epochs: 10
        validation-interval: 0.25
        validation-batches: 50

        logger-interval: 100
        nmbr-logged-images: 9
        checkpoint-interval: 1

model: !include nets/shallow_feature_net.yaml
        
                
