dataset:
        name: "road_boundary_dataset"
        #size: [640, 360]
        #size: [1280, 720]
        size: null
        train-dataset: "data/lyft-lvl5-15x10/train"
        valid-dataset: "data/lyft-lvl5-15x10/valid"
        test-dataset: "data/lyft-lvl5-15x10/test"
        angle_bins: null
        augmentation: 0.2

train:
        gpus: 0
        distributed_backend: null
        log_gpu_memory: True
        profiler: False

        learning-rate: 1.0e-4
        lr-decay: 0.1
        lr_decay_step_size: 2
        weight_decay: 1.0e-4 

        batch-size: 6
        accumulate_grad_batches: 5

        losses: 
                distance_loss: 
                        loss: "mse"
                        factor: 0.0
                        args:
                                reduction: "mean"
                end_loss: 
                        loss: "bce"
                        factor: 0.0
                        args:
                                reduction: "mean"
                direction_loss: 
                        loss: "cosine_similarity"
                        factor: 1.0
                        args:
                                reduction: "mean"

        epochs: 100
        validation-interval: 0.5
        validation-batches: 50

        logger-interval: 100
        nmbr-logged-images: 9
        checkpoint-interval: 1

model: nets/shallow_feature_net.yaml
        
                
