dataset:
        name: "road_boundary_dataset"
        #size: [640, 360]
        #size: [1280, 720]
        size: null
        train-dataset: "data/nuscenes-complete-15x10/train"
        valid-dataset: "data/nuscenes-complete-15x10/valid"
        test-dataset: "data/nuscenes-complete-15x10/test"

train:
        gpus: 0
        distributed_backend: null
        log_gpu_memory: True
        profiler: False

        learning-rate: 0.02
        lr-decay: 0.1
        lr_decay_step_size: 1
        weight_decay: 1e-1

        batch-size: 7
        accumulate_grad_batches: 4

        losses: 
                distance_loss: 
                        loss: "mse"
                        factor: 1.0
                        args:
                                reduction: "mean"
                end_loss: 
                        loss: "bce"
                        factor: 1.0
                        args:
                                reduction: "mean"
                direction_loss: 
                        loss: "cosine_similarity"
                        factor: 1.0
                        args:
                                reduction: "mean"

        epochs: 100
        validation-interval: 0.25
        validation-batches: 50

        logger-interval: 100
        nmbr-logged-images: 9
        checkpoint-interval: 1

model: nets/shallow_feature_net.yaml
        
                
