dataset:
        #size: [640, 360]
        size: [1280, 720]
        train-dataset: "data/nuscenes-complete-15x10/train"
        valid-dataset: "data/nuscenes-complete-15x10/valid"

train:
        learning-rate: 0.001
        batch-size: 2
        weight_decay: 0.0004

        epochs: 15

        checkpoint-interval: 1

model:
        use_custom_encoder: false
        encoder: "resnet18"
        encoder_weights: "imagenet"
        encoder_depth: 2
        activation: "sigmoid"
        decoder_use_batchnorm: true

        head: [
                {
                in_channels: [64, 8, 8],
                out_channels: [8, 8, 1],
                kernel_sizes: [3, 3, 1],
                strides: 1,
                padding: [1,1,0],
                dilation: 1,
                batch_norm: True,
                end_activation: "relu"},

                {
                in_channels: [64, 8, 8],
                out_channels: [8, 8, 1],
                kernel_sizes: [3, 3, 1],
                strides: 1,
                padding: [1,1,0],
                dilation: 1,
                batch_norm: True,
                end_activation: "relu"},

                {
                in_channels: [64, 8, 8],
                out_channels: [8, 8, 2],
                kernel_sizes: [3, 3, 1],
                strides: 1,
                padding: [1,1,0],
                dilation: 1,
                batch_norm: True,
                end_activation: "sigmoid"},
        ]
                
