dataset:
    name: road_boundary_dataset
        #size: [640, 360]
        #size: [1280, 720]
    size:
    train-dataset: data/lyft-lvl5-15x10/train
    valid-dataset: data/lyft-lvl5-15x10/valid
    test-dataset: data/lyft-lvl5-15x10/test
    angle_bins:
    augmentation: 0.3

train:
    gpus: 0
    distributed_backend:
    log_gpu_memory: true
    profiler: false

    resume_training: false
    load_weights: false
    checkpoint_path: data/checkpoints/

    learning-rate: 1.0e-2
    lr-decay: 0.5
    lr_decay_patience: 2
    weight_decay: 1.0e-4

    batch-size: 3
    accumulate_grad_batches: 10

    losses:
        distance_loss:
            loss: mse
            factor: 1.0
            args:
                reduction: mean
        end_loss:
            loss: bce
            factor: 10.0
            args:
                reduction: mean
        direction_loss:
            loss: cosine_similarity
            factor: 10.0
            args:
                reduction: mean

    epochs: 100
    validation-interval: 0.5
    validation-batches: 50

    logger-interval: 100
    nmbr-logged-images: 9
    checkpoint-interval: 1

model: nets/feature_net.yaml
