dataset:
        size: [1280, 720]
        train-dataset: "data/train"
        test-dataset: "data/test"

train:
        learning-rate: 0.001
        batch-size: 1
        weight_decay: 1e-4

        epochs: 100
        eval-intervall: 10

        checkpoint-interval: 10

models:
        use_custom_encoder: false
        encoder: "resnet18"
        encoder_weights: "imagenet"
        encoder_depth: 2
        activation: "relu"
        decoder_use_batchnorm: true

        head: [
                {
                in_channels: [64, 8, 8],
                out_channels: [8, 8, 8],
                kernel_size: [3, 3, 1],
                strides: 1,
                padding: [1,1,0],
                dilation: 0,
                batch_norm: True,
                end_activation: "relu"},

                {
                in_channels: [64, 8, 8],
                out_channels: [8, 8, 8],
                kernel_size: [3, 3, 1],
                strides: 1,
                padding: [1,1,0],
                dilation: 1,
                batch_norm: True,
                end_activation: "relu"},

                {
                in_channels: [64, 8, 8],
                out_channels: [8, 8, 8],
                kernel_size: [3, 3, 1],
                strides: 1,
                padding: [1,1,0],
                dilation: 1,
                batch_norm: True,
                end_activation: "relu"},
        ]
                
